//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeechRecognition
{
    using System;
    using System.Collections.Generic;
    
    public partial class comands
    {
        public string comand { get; set; }
        public string vopros { get; set; }
    }
}
